import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import { ClerkProvider } from "@clerk/nextjs";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="bg-black min-h-screen>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
 <Navbar/>
 <div className="flex-1 bg-[#000000] w-full ">
  <main className="max-w-6xl mx-auto">
  {children}
  </main>
 </div>
      
      </body>
    </html>
    </ClerkProvider>
    
  );
}
